matrix:
  fast_finish: true
  include:
    # - language: go
    #   go:
    #     - "1.11"
    #   install: true
    #   before_script:
    #     - cd 2018
    #   script:
    #     - ./test.sh

    - language: node_js
      node_js:
        - "lts/gallium"
      before_script:
        - cd 2021
        - yarn
      script:
        - yarn test
