matrix:
  fast_finish: true
  include:
    - language: go
      go:
        - "1.11"
      before_script:
        - cd 2018
      script:
        - ./test.sh

    - language: nodejs
      node:
        - "lts/erbium"
      before_script:
        - cd 2019
        - yarn
      script:
        - yarn test
