matrix:
  include:
    - language: go
      go:
        - "1.13"
      before_script:
        - cd 2018
      script:
        - ./test.sh

    - language: nodejs
      node:
        - 12
      before_script:
        - cd 2019
        - yarn
      script:
        - yarn test
